<a href="<?php echo $this->url(array('controller' => 'tema',
                                     'action' => 'add'//, 'id' => $d->id
                                    )); ?>">Agregar Tema</a>

<table>
    <tr>
        <th>Titulo</th>
        <th>Album</th>
        <th>Duracion</th>
        <th>Borrar</th>
    </tr>
    <?php foreach ($this->datos as $d) : ?>
        <tr>
            <td>
                <a href="<?php echo $this->url(array('controller' => 'tema',
            'action' => 'update', 'id' => $d->id)); ?>">
                   <?php echo $d->titulo; ?>
            </a>
        </td>
        <td><?php echo $this->escape($d->album_id); ?></td>
        <td><?php echo $this->escape($d->duracion); ?></td>
        <td>

            <a href="<?php echo $this->url(array('controller' => 'tema',
                       'action' => 'delete', 'id' => $d->id)); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>