<!--creo link para agregar un album -->
<a href="<?php echo $this->url(array('controller' => 'album',
                                     'action'     => 'add'
                                     //'id'         => $d->id
                                    )
                              );
                                      ?>"
                                      >Agregar Album</a>

<!--creo una tabla para mostrar los datos-->
<table>
    <tr>
        <th>Nombre</th>
        <th>Artista</th>
        <th>Fecha</th>
        <th>Descripcion</th>
        <th>Borrar</th>
    </tr>
<!--    recorro el arreglo de datos-->
    <?php foreach ($this->datos as $d) : ?>
<!--           por cada fila, muestro sus datos -->
        <tr>
<!--            nombre del album, con un enlace para editar el album-->
            <td>
                <a href="<?php echo $this->url(array('controller' => 'album',
            'action' => 'update', 'id' => $d->id)); ?>">
                   <?php echo $d->nombre; ?>
            </a>
        </td>
<!--                id del artista-->
        <td><?php echo $this->escape($d->artista_id); ?></td>
<!--                    fecha del album-->
        <td><?php echo $this->escape($d->fecha); ?></td>
<!--                        descripcion-->
        <td><?php echo $d->descripcion; ?></td>
<!--                   enlace para borrar el album-->
        <td>

            <a href="<?php echo $this->url(array('controller' => 'album',
                       'action' => 'delete', 'id' => $d->id)); ?>">Delete</a>
            </td>
        </tr>
<!--    fin del for-->
    <?php endforeach; ?>
</table>