<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <head>
        <title><?php echo $this->title; ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!--        referencia al archivo css, uso $this->baseUrl para tener una referencia segun
        el lugar dede donde se llame al layout-->
        <link href="<?php echo $this->baseUrl(); ?>/css/estilo.css" type="text/css" rel="stylesheet">
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/javascript/jquery/jquery-1.9.1.js"></script>
    </head>
    <body>
        <div class="cabecera">
<!--           imagen, tambien uso $this->baseUrl para referenciarla-->
<a href="http://derasten.com"><img src="<?php echo $this->baseUrl(); ?>/images/Cabecera-derasten.png" width="1000" height="211" alt="header"/></a>
        </div>
        <h1><?php echo $this->title; ?></h1>

        <h3>Este es el contenido de la vista:</h3>
        <div class="contenido">
<!--            muestro el contenido segun la vista-->
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>